export const Canchas = [
  {
    id: 1,
    star: 4,
    title: "Internacional Golazo",
    description: "Cancha de grass sintetico 40 de largo x 20 ancho",
    price: 60,
    completed: false,
    latitude: 0,
    longitude: 0
  },
  {
    id: 2,
    star: 3,
    title: "Mundialito TACNA",
    description: "Cancha de grass sintetico 60 de largo x 30 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 3,
    star: 5,
    title: "TOP GOL",
    description: "Cancha de grass sintetico 50 de largo x 25 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 4,
    star: 4,
    title: "Cancha Cortec",
    description: "Cancha de grass sintetico 60 de largo x 40 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 5,
    star: 5,
    title: "Defensores",
    description: "Cancha de grass sintetico 40 de largo x 20 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 6,
    star: 4,
    title: "Quinta Gutiérrez",
    description: "Cancha de grass sintetico 40 de largo x 20 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 7,
    star: 4,
    title: "Don Hector",
    description: "Cancha de grass sintetico 80 de largo x 40 ancho",
    price: 80,
    completed: false,
  },
  {
    id: 8,
    star: 4,
    title: "28 de Agosto",
    description: "Cancha de grass sintetico 50 de largo x 25 ancho",
    price: 60,
    completed: false,
  },
];
