export const Canchas = [
  {
    id: 1,
    star: 4,
    title: "Barra Gol",
    description: "Cancha de grass sintetico 40 de largo x 20 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 2,
    star: 3,
    title: "Super Pichanga",
    description: "Cancha de grass sintetico 60 de largo x 30 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 3,
    star: 5,
    title: "Hector Cancha",
    description: "Cancha de grass sintetico 50 de largo x 25 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 4,
    star: 4,
    title: "Super Campeones",
    description: "Cancha de grass sintetico 60 de largo x 40 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 5,
    star: 5,
    title: "Defensores",
    description: "Cancha de grass sintetico 40 de largo x 20 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 6,
    star: 4,
    title: "28 de Agosto",
    description: "Cancha de grass sintetico 40 de largo x 20 ancho",
    price: 60,
    completed: false,
  },
  {
    id: 7,
    star: 4,
    title: "Cachipucara",
    description: "Cancha de grass sintetico 80 de largo x 40 ancho",
    price: 80,
    completed: false,
  },
  {
    id: 8,
    star: 4,
    title: "Puro Gol",
    description: "Cancha de grass sintetico 50 de largo x 25 ancho",
    price: 60,
    completed: false,
  },
];
